# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'activerecord',             '7.2.2.1'
gem 'bundler',                  '>= 2.5.13'
gem 'factory_bot',              '6.5.6'
gem 'pry',                      '0.14.2'
gem 'pry-nav',                  '1.0.0'
gem 'nokogiri',                 '1.19.1'
gem 'rails',                    '7.2.2.1'
gem 'rails-controller-testing', '1.0.5'
gem 'rake',                     '13.2.1'
gem 'reek',                     '6.5.0'
gem 'rspec',                    '3.13.2'
gem 'rspec-core',               '3.13.6'
gem 'rspec-expectations',       '3.13.5'
gem 'rspec-mocks',              '3.13.8'
gem 'rspec-support',            '3.13.7'
gem 'rspec-rails',              '8.0.3'
gem 'rubocop',                  '1.85.1'
gem 'rubocop-rspec',            '3.9.0'
gem 'rubycritic',               '5.0.0'
gem 'shoulda-matchers',         '6.5.0'
gem 'simplecov',                '0.22.0'
gem 'simplecov-html',           '0.13.2'
gem 'simplecov-lcov',           '0.9.0'
gem 'sprockets-rails'#,          '4.2.2'
gem 'sqlite3',                  '1.4.2'
gem 'yard',                     '0.9.38'
gem 'yardstick',                '0.9.9'
gem 'tzinfo-data',              '2.0.6'
