# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'actionpack',               '7.0.4.3'
gem 'activerecord',             '7.0.4.3'
gem 'bundler',                  '>= 2.3.25'
gem 'factory_bot',              '5.2.0'
gem 'nokogiri',                 '1.12.5'
gem 'pry',                      '0.12.2'
gem 'pry-nav',                  '0.3.0'
gem 'rails',                    '7.0.4.3'
gem 'rails-controller-testing', '1.0.4'
gem 'rake',                     '13.0.1'
gem 'reek',                     '6.0.3'
gem 'rspec',                    '3.9.0'
gem 'rspec-core',               '3.9.3'
gem 'rspec-expectations',       '3.9.4'
gem 'rspec-mocks',              '3.9.1'
gem 'rspec-rails',              '3.9.1'
gem 'rspec-support',            '3.9.4'
gem 'rubocop',                  '0.80.1'
gem 'rubocop-rspec',            '1.38.1'
gem 'rubycritic',               '4.6.1'
gem 'simplecov',                '0.17.1'
gem 'sprockets-rails',          '3.4.2'
gem 'sqlite3',                  '1.4.2'
gem 'tzinfo-data',              '~> 1.2022.1'
gem 'yard',                     '0.9.26'
gem 'yardstick',                '0.9.9'
gem 'simplecov-lcov',           '0.9.0'
